name: 'Generate PR Summary'
description: 'Generate a concise 2-3 sentence summary of what a PR does'
inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  pr-number:
    description: 'PR number to summarize'
    required: true
  openai-api-key:
    description: 'OpenAI API key'
    required: false
    default: ''
outputs:
  summary:
    description: '2-3 sentence summary of what the PR does'
    value: ${{ steps.generate.outputs.summary }}
  has-summary:
    description: 'Boolean - whether summary was generated successfully'
    value: ${{ steps.generate.outputs.has-summary }}

runs:
  using: 'composite'
  steps:
    - name: Check if API key is available
      id: check-key
      shell: bash
      env:
        API_KEY: ${{ inputs.openai-api-key }}
      run: |
        if [ -z "$API_KEY" ]; then
          echo "has-key=false" >> "$GITHUB_OUTPUT"
          echo "OpenAI API key not configured - skipping summary generation"
        else
          echo "has-key=true" >> "$GITHUB_OUTPUT"
          echo "OpenAI API key available"
        fi

    - name: Get PR content
      id: get-pr
      if: steps.check-key.outputs.has-key == 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        PR_NUMBER: ${{ inputs.pr-number }}
      run: |
        echo "Fetching PR content..."
        
        # Get PR title
        pr_title=$(gh pr view "$PR_NUMBER" --json title --jq '.title')
        
        # Get PR body (limited)
        pr_body=$(gh pr view "$PR_NUMBER" --json body --jq '.body' | head -c 2000 || true)
        
        # Get changed files list
        files=$(gh pr view "$PR_NUMBER" --json files --jq '.files[].path' | head -n 30 | tr '\n' ', ' || true)
        
        echo "pr-title=$pr_title" >> "$GITHUB_OUTPUT"
        echo "files=$files" >> "$GITHUB_OUTPUT"
        
        echo "pr-body<<EOF" >> "$GITHUB_OUTPUT"
        echo "$pr_body" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"

    - name: Generate summary
      id: generate
      shell: bash
      env:
        HAS_KEY: ${{ steps.check-key.outputs.has-key }}
        OPENAI_API_KEY: ${{ inputs.openai-api-key }}
        PR_TITLE: ${{ steps.get-pr.outputs.pr-title }}
        PR_BODY: ${{ steps.get-pr.outputs.pr-body }}
        FILES: ${{ steps.get-pr.outputs.files }}
      run: |
        if [ "$HAS_KEY" = "false" ]; then
          echo "summary=" >> "$GITHUB_OUTPUT"
          echo "has-summary=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi
        
        echo "Generating PR summary..."
        
        # System prompt for summary generation
        SYSTEM_PROMPT="You are a helpful assistant that summarizes pull requests. Given a PR title, description, and list of changed files, write a concise 2-3 sentence summary of what the PR does. Focus on the purpose and main changes. Do not judge the quality or make suggestions. Just describe what it does in plain language."
        
        # Build user message
        USER_MSG=$(printf "PR Title: %s\n\nPR Description:\n%s\n\nFiles changed:\n%s\n\nWrite a 2-3 sentence summary of what this PR does." "$PR_TITLE" "$PR_BODY" "$FILES")
        
        # Build JSON payload using jq
        payload=$(jq -n \
          --arg model "gpt-4o-mini" \
          --arg system_prompt "$SYSTEM_PROMPT" \
          --arg user_msg "$USER_MSG" \
          '{"model":$model,"messages":[{"role":"system","content":$system_prompt},{"role":"user","content":$user_msg}],"temperature":0.3,"max_tokens":150}')
        
        # Call OpenAI API
        response=$(curl -s -X POST https://api.openai.com/v1/chat/completions \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $OPENAI_API_KEY" \
          -d "$payload")
        
        # Check for API errors
        api_error=$(echo "$response" | jq -r '.error.message // ""')
        if [ -n "$api_error" ]; then
          echo "WARNING: OpenAI API error: $api_error"
          echo "summary=" >> "$GITHUB_OUTPUT"
          echo "has-summary=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi
        
        # Extract summary
        summary=$(echo "$response" | jq -r '.choices[0].message.content // ""')
        
        if [ -z "$summary" ]; then
          echo "WARNING: Empty response from AI"
          echo "summary=" >> "$GITHUB_OUTPUT"
          echo "has-summary=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi
        
        echo "Summary generated successfully"
        
        # Output using heredoc for multiline
        echo "summary<<EOF" >> "$GITHUB_OUTPUT"
        echo "$summary" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"
        echo "has-summary=true" >> "$GITHUB_OUTPUT"

