name: 'Detect Changed Areas'
description: 'Detect which areas of the codebase were changed (frontend, backend, datasources, etc.)'
inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  pr-number:
    description: 'Pull request number'
    required: true
outputs:
  areas:
    description: 'Comma-separated list of affected areas'
    value: ${{ steps.detect.outputs.areas }}
  area-labels:
    description: 'Comma-separated list of area labels to apply'
    value: ${{ steps.detect.outputs.area-labels }}
  primary-area:
    description: 'The primary area (most files changed)'
    value: ${{ steps.detect.outputs.primary-area }}

runs:
  using: 'composite'
  steps:
    - name: Get changed files
      id: files
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        PR_NUMBER: ${{ inputs.pr-number }}
      run: |
        # Get all changed file paths
        changed_files=$(gh pr view "$PR_NUMBER" --json files --jq '.files[].path')
        echo "changed-files<<EOF" >> "$GITHUB_OUTPUT"
        echo "$changed_files" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"

    - name: Detect areas
      id: detect
      shell: bash
      env:
        CHANGED_FILES: ${{ steps.files.outputs.changed-files }}
      run: |
        declare -A area_counts
        areas=()
        labels=()
        
        # Analyze each file
        while IFS= read -r file; do
          if [ -z "$file" ]; then continue; fi
          
          # Docs
          if echo "$file" | grep -qE '^(docs/|contribute/|.*\.md$)'; then
            area_counts[docs]=$((${area_counts[docs]:-0} + 1))
          fi
          
          # Frontend
          if echo "$file" | grep -qE '^(public/|packages/.*\.(ts|tsx|js|jsx)$)'; then
            area_counts[frontend]=$((${area_counts[frontend]:-0} + 1))
          fi
          
          # Backend
          if echo "$file" | grep -qE '\.go$'; then
            area_counts[backend]=$((${area_counts[backend]:-0} + 1))
          fi
          
          # Alerting
          if echo "$file" | grep -qE '^(pkg/services/ngalert|pkg/services/alerting|public/app/features/alerting)'; then
            area_counts[alerting]=$((${area_counts[alerting]:-0} + 1))
          fi
          
          # Explore
          if echo "$file" | grep -qE '^public/app/features/explore'; then
            area_counts[explore]=$((${area_counts[explore]:-0} + 1))
          fi
          
          # Dashboards
          if echo "$file" | grep -qE '^(public/app/features/dashboard|apps/dashboard)'; then
            area_counts[dashboard]=$((${area_counts[dashboard]:-0} + 1))
          fi
          
          # Datasources
          if echo "$file" | grep -qE '^(public/app/plugins/datasource|pkg/tsdb)'; then
            # Try to detect specific datasource
            if echo "$file" | grep -q "prometheus"; then
              area_counts[datasource-prometheus]=$((${area_counts[datasource-prometheus]:-0} + 1))
            elif echo "$file" | grep -q "loki"; then
              area_counts[datasource-loki]=$((${area_counts[datasource-loki]:-0} + 1))
            elif echo "$file" | grep -q "azuremonitor"; then
              area_counts[datasource-azure]=$((${area_counts[datasource-azure]:-0} + 1))
            elif echo "$file" | grep -q "cloudwatch"; then
              area_counts[datasource-cloudwatch]=$((${area_counts[datasource-cloudwatch]:-0} + 1))
            else
              area_counts[datasources]=$((${area_counts[datasources]:-0} + 1))
            fi
          fi
          
          # Build/CI
          if echo "$file" | grep -qE '^(\.github/workflows|scripts/build|packaging/)'; then
            area_counts[build]=$((${area_counts[build]:-0} + 1))
          fi
          
          # Tests
          if echo "$file" | grep -qE '(test|spec|e2e)'; then
            area_counts[tests]=$((${area_counts[tests]:-0} + 1))
          fi
        done <<< "$CHANGED_FILES"
        
        # Convert to arrays and find primary area
        max_count=0
        primary_area=""
        
        for area in "${!area_counts[@]}"; do
          count=${area_counts[$area]}
          areas+=("$area")
          
          # Map to Grafana labels
          case "$area" in
            frontend) labels+=("area/frontend") ;;
            backend) labels+=("area/backend") ;;
            docs) labels+=("type/docs") ;;
            alerting) labels+=("area/alerting") ;;
            explore) labels+=("area/explore") ;;
            dashboard) labels+=("area/dashboard") ;;
            datasource-*) labels+=("datasource/${area#datasource-}") ;;
            datasources) labels+=("area/datasources") ;;
            build) labels+=("type/build-packaging") ;;
          esac
          
          if [ $count -gt $max_count ]; then
            max_count=$count
            primary_area="$area"
          fi
        done
        
        # Join arrays
        areas_str=$(IFS=,; echo "${areas[*]}")
        labels_str=$(IFS=,; echo "${labels[*]}")
        
        echo "areas=$areas_str" >> "$GITHUB_OUTPUT"
        echo "area-labels=$labels_str" >> "$GITHUB_OUTPUT"
        echo "primary-area=$primary_area" >> "$GITHUB_OUTPUT"
        
        echo "✅ Detected areas: $areas_str"
        echo "✅ Primary area: $primary_area"

