name: 'External Monitor Workflows'
description: 'Monitor existing Grafana CI/CD workflows without running duplicates'
inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  pr-number:
    description: 'PR number to monitor'
    required: true
  pr-type:
    description: 'PR type: docs, bugfix, or feature'
    required: true
outputs:
  all-passed:
    description: 'Boolean - true if all relevant workflows passed'
    value: ${{ steps.check-workflows.outputs.all-passed }}
  results-json:
    description: 'JSON object with per-workflow status'
    value: ${{ steps.check-workflows.outputs.results-json }}
  summary-text:
    description: 'Human-readable summary for comment'
    value: ${{ steps.check-workflows.outputs.summary-text }}

runs:
  using: 'composite'
  steps:
    - name: Determine workflows to monitor
      id: determine-workflows
      shell: bash
      env:
        PR_TYPE: ${{ inputs.pr-type }}
      run: |
        # Determine which workflows to monitor based on PR type
        if [ "$PR_TYPE" = "docs" ]; then
          # Docs PRs: only monitor docs linting
          WORKFLOWS="Lint"
          echo "workflows=$WORKFLOWS" >> "$GITHUB_OUTPUT"
          echo "Monitoring docs workflows: $WORKFLOWS"
        else
          # Bugfix and Feature PRs: monitor linting and tests
          # Note: Using the actual check names from GitHub status API
          WORKFLOWS="Lint,lint-go,All backend unit tests complete"
          echo "workflows=$WORKFLOWS" >> "$GITHUB_OUTPUT"
          echo "Monitoring code workflows: $WORKFLOWS"
        fi

    - name: Check workflow statuses
      id: check-workflows
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        PR_NUMBER: ${{ inputs.pr-number }}
        WORKFLOWS: ${{ steps.determine-workflows.outputs.workflows }}
      run: |
        echo "Checking workflows for PR #$PR_NUMBER: $WORKFLOWS"
        
        # Get PR head SHA
        pr_sha=$(gh pr view "$PR_NUMBER" --json headRefOid --jq '.headRefOid')
        echo "PR SHA: $pr_sha"
        
        # Initialize results
        all_passed=true
        results=()
        summary_lines=()
        
        # Check each workflow using the checks API (which has the actual status check names)
        IFS=',' read -ra WORKFLOW_ARRAY <<< "$WORKFLOWS"
        for workflow_name in "${WORKFLOW_ARRAY[@]}"; do
          echo "Checking workflow: $workflow_name"
          
          # Get check status for this PR using checks API
          check_status=$(gh api \
            "/repos/${{ github.repository }}/commits/$pr_sha/check-runs" \
            --jq ".check_runs[] | select(.name == \"$workflow_name\") | {status: .status, conclusion: .conclusion} | @json" \
            | head -n 1)
          
          if [ -z "$check_status" ]; then
            # Check hasn't run yet
            status="pending"
            conclusion="none"
            results+=("{\"workflow\":\"$workflow_name\",\"status\":\"pending\",\"conclusion\":\"none\"}")
            summary_lines+=("- [ ] $workflow_name (pending)")
            all_passed=false
          else
            status=$(echo "$check_status" | jq -r '.status')
            conclusion=$(echo "$check_status" | jq -r '.conclusion')
            
            if [ "$status" = "completed" ]; then
              if [ "$conclusion" = "success" ]; then
                results+=("{\"workflow\":\"$workflow_name\",\"status\":\"completed\",\"conclusion\":\"success\"}")
                summary_lines+=("- [x] $workflow_name")
              elif [ "$conclusion" = "failure" ]; then
                results+=("{\"workflow\":\"$workflow_name\",\"status\":\"completed\",\"conclusion\":\"failure\"}")
                summary_lines+=("- [ ] ~~$workflow_name~~ **FAILED**")
                all_passed=false
              else
                # skipped, cancelled, etc
                results+=("{\"workflow\":\"$workflow_name\",\"status\":\"completed\",\"conclusion\":\"$conclusion\"}")
                summary_lines+=("- [ ] $workflow_name ($conclusion)")
                all_passed=false
              fi
            else
              # in_progress or queued
              results+=("{\"workflow\":\"$workflow_name\",\"status\":\"$status\",\"conclusion\":\"none\"}")
              summary_lines+=("- [ ] $workflow_name ($status)")
              all_passed=false
            fi
          fi
        done
        
        # Build JSON array
        results_json="[$(IFS=,; echo "${results[*]}")]"
        echo "results-json=$results_json" >> "$GITHUB_OUTPUT"
        
        # Build summary text
        summary_text=$(printf '%s\n' "${summary_lines[@]}")
        echo "summary-text<<EOF" >> "$GITHUB_OUTPUT"
        echo "$summary_text" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"
        
        # Set all-passed output
        echo "all-passed=$all_passed" >> "$GITHUB_OUTPUT"
        
        echo "All workflows passed: $all_passed"
        echo "Summary:"
        echo "$summary_text"

