name: 'Check PR Requirements'
description: 'Check if PR meets contribution requirements (description, issue reference, changelog, etc.)'
inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  pr-number:
    description: 'Pull request number'
    required: true
outputs:
  all-requirements-met:
    description: 'Whether all requirements are met'
    value: ${{ steps.check.outputs.all-requirements-met }}
  has-description:
    description: 'Whether PR has a proper description'
    value: ${{ steps.check.outputs.has-description }}
  has-issue-reference:
    description: 'Whether PR references an issue'
    value: ${{ steps.check.outputs.has-issue-reference }}
  has-changelog-label:
    description: 'Whether PR has a changelog decision label'
    value: ${{ steps.check.outputs.has-changelog-label }}
  commit-format-valid:
    description: 'Whether commit messages follow format'
    value: ${{ steps.check.outputs.commit-format-valid }}
  missing-requirements:
    description: 'List of missing requirements'
    value: ${{ steps.check.outputs.missing-requirements }}

runs:
  using: 'composite'
  steps:
    - name: Get PR details
      id: pr-info
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        PR_NUMBER: ${{ inputs.pr-number }}
      run: |
        # Get PR body
        pr_body=$(gh pr view "$PR_NUMBER" --json body --jq '.body')
        echo "pr-body<<EOF" >> "$GITHUB_OUTPUT"
        echo "$pr_body" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"
        
        # Get PR title
        pr_title=$(gh pr view "$PR_NUMBER" --json title --jq '.title')
        echo "pr-title=$pr_title" >> "$GITHUB_OUTPUT"
        
        # Get labels
        labels=$(gh pr view "$PR_NUMBER" --json labels --jq '.labels[].name' | tr '\n' ',' | sed 's/,$//')
        echo "labels=$labels" >> "$GITHUB_OUTPUT"
        
        # Get commits
        commits=$(gh pr view "$PR_NUMBER" --json commits --jq '.commits[].messageHeadline')
        echo "commits<<EOF" >> "$GITHUB_OUTPUT"
        echo "$commits" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"

    - name: Check requirements
      id: check
      shell: bash
      env:
        PR_BODY: ${{ steps.pr-info.outputs.pr-body }}
        PR_TITLE: ${{ steps.pr-info.outputs.pr-title }}
        LABELS: ${{ steps.pr-info.outputs.labels }}
        COMMITS: ${{ steps.pr-info.outputs.commits }}
      run: |
        missing=()
        
        # Check 1: PR has a meaningful description (not just template)
        if [ ${#PR_BODY} -lt 50 ] || echo "$PR_BODY" | grep -q "<!-- Please provide a clear and concise description"; then
          echo "has-description=false" >> "$GITHUB_OUTPUT"
          missing+=("❌ PR description is too short or still contains template text")
        else
          echo "has-description=true" >> "$GITHUB_OUTPUT"
          echo "✅ PR has a proper description"
        fi
        
        # Check 2: PR references an issue
        if echo "$PR_BODY" | grep -qiE "(close|closes|closed|fix|fixes|fixed|resolve|resolves|resolved) #[0-9]+"; then
          echo "has-issue-reference=true" >> "$GITHUB_OUTPUT"
          echo "✅ PR references an issue"
        else
          echo "has-issue-reference=false" >> "$GITHUB_OUTPUT"
          missing+=("⚠️ PR should reference an issue (Closes #XXX)")
        fi
        
        # Check 3: Changelog decision label
        if echo "$LABELS" | grep -qE "(add to changelog|no-changelog|Changelog"; then
          echo "has-changelog-label=true" >> "$GITHUB_OUTPUT"
          echo "✅ Changelog decision label present"
        else
          echo "has-changelog-label=false" >> "$GITHUB_OUTPUT"
          missing+=("⚠️ Please add a changelog decision label")
        fi
        
        # Check 4: Commit message format
        # Grafana convention: Area: Description
        invalid_commits=0
        while IFS= read -r commit; do
          if [ -z "$commit" ]; then continue; fi
          
          # Check if commit follows "Area: Description" format
          if ! echo "$commit" | grep -qE '^[A-Z][a-zA-Z]+:'; then
            invalid_commits=$((invalid_commits + 1))
          fi
        done <<< "$COMMITS"
        
        if [ $invalid_commits -eq 0 ]; then
          echo "commit-format-valid=true" >> "$GITHUB_OUTPUT"
          echo "✅ Commit messages follow format"
        else
          echo "commit-format-valid=false" >> "$GITHUB_OUTPUT"
          missing+=("⚠️ $invalid_commits commit(s) don't follow 'Area: Description' format")
        fi
        
        # Set overall status
        if [ ${#missing[@]} -eq 0 ]; then
          echo "all-requirements-met=true" >> "$GITHUB_OUTPUT"
          echo "✅ All requirements met!"
        else
          echo "all-requirements-met=false" >> "$GITHUB_OUTPUT"
          echo "⚠️ Some requirements not met"
        fi
        
        # Format missing requirements
        missing_formatted=$(printf '%s\n' "${missing[@]}")
        echo "missing-requirements<<EOF" >> "$GITHUB_OUTPUT"
        echo "$missing_formatted" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"

