name: 'External Post Validation Comment'
description: 'Generate and post consolidated validation comment with todo list, workflow status, and AI feedback'
inputs:
  github-token:
    description: 'GitHub token for posting comment'
    required: true
  pr-number:
    description: 'PR to comment on'
    required: true
  pr-type:
    description: 'PR type: docs, bugfix, or feature'
    required: true
  pr-size:
    description: 'PR size: small, medium, or large'
    required: true
  workflow-results:
    description: 'JSON from external-monitor-workflows'
    required: true
  workflow-summary:
    description: 'Summary text from external-monitor-workflows'
    required: true
  ai-feedback:
    description: 'Feedback text from external-assess-quality'
    required: false
    default: ''
  template-path:
    description: 'Path to appropriate todo template'
    required: true
outputs:
  comment-posted:
    description: 'Boolean - whether comment was successfully posted'
    value: ${{ steps.post-comment.outputs.comment-posted }}

runs:
  using: 'composite'
  steps:
    - name: Extract template section
      id: extract-template
      shell: bash
      env:
        TEMPLATE_PATH: ${{ inputs.template-path }}
        PR_TYPE: ${{ inputs.pr-type }}
      run: |
        # Read the template file
        if [ ! -f "$TEMPLATE_PATH" ]; then
          echo "❌ Template not found: $TEMPLATE_PATH"
          exit 1
        fi
        
        template_content=$(cat "$TEMPLATE_PATH")
        
        # Extract the appropriate section based on PR type
        case "$PR_TYPE" in
          docs)
            # Extract DOCS section (between <!-- DOCS SECTION --> and first ---)
            section=$(echo "$template_content" | awk '/<!-- DOCS SECTION -->/,/^---$/' | sed '1d;$d')
            ;;
          bugfix)
            # Extract BUGFIX section
            section=$(echo "$template_content" | awk '/<!-- BUGFIX SECTION -->/,/^---$/' | sed '1d;$d')
            ;;
          feature)
            # Extract FEATURE section (after last ---) 
            section=$(echo "$template_content" | awk '/<!-- FEATURE SECTION -->/,0' | sed '1d')
            ;;
          *)
            echo "❌ Unknown PR type: $PR_TYPE"
            exit 1
            ;;
        esac
        
        echo "template-section<<EOF" >> "$GITHUB_OUTPUT"
        echo "$section" >> "$GITHUB_OUTPUT"
        echo "EOF" >> "$GITHUB_OUTPUT"
        
        echo "✅ Extracted $PR_TYPE section from template"

    - name: Build comment
      id: build-comment
      shell: bash
      env:
        PR_TYPE: ${{ inputs.pr-type }}
        PR_SIZE: ${{ inputs.pr-size }}
        TEMPLATE_SECTION: ${{ steps.extract-template.outputs.template-section }}
        WORKFLOW_SUMMARY: ${{ inputs.workflow-summary }}
        AI_FEEDBACK: ${{ inputs.ai-feedback }}
      run: |
        # Map type to emoji
        case "$PR_TYPE" in
          docs) TYPE_EMOJI="📝" TYPE_NAME="Documentation" ;;
          bugfix) TYPE_EMOJI="🐛" TYPE_NAME="Bugfix" ;;
          feature) TYPE_EMOJI="✨" TYPE_NAME="Feature" ;;
        esac
        
        # Map size to emoji
        case "$PR_SIZE" in
          small) SIZE_EMOJI="🟢" ;;
          medium) SIZE_EMOJI="🟡" ;;
          large) SIZE_EMOJI="🔴" ;;
        esac
        
        # Build the comment
        cat > /tmp/validation-comment.md <<EOF
        ## ${TYPE_EMOJI} ${TYPE_NAME} PR Validation ${SIZE_EMOJI} (${PR_SIZE})
        
        ${TEMPLATE_SECTION}
        
        ### Automated Checks
        ${WORKFLOW_SUMMARY}
        
        EOF
        
        # Add AI feedback if available
        if [ -n "$AI_FEEDBACK" ] && [ "$AI_FEEDBACK" != "*AI assessment skipped*" ]; then
          cat >> /tmp/validation-comment.md <<EOF
        ### 🤖 Quick Review
        ${AI_FEEDBACK}
        
        EOF
        fi
        
        # Add footer
        cat >> /tmp/validation-comment.md <<EOF
        ---
        💡 **Push updates anytime** - this checklist updates automatically!  
        See our [External PR Workflow Guide](../contribute/external-pr-workflow.md) for more details.
        
        <!-- external-pr-validation-comment -->
        EOF
        
        echo "✅ Comment built successfully"
        cat /tmp/validation-comment.md

    - name: Post or update comment
      id: post-comment
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        PR_NUMBER: ${{ inputs.pr-number }}
      run: |
        echo "Looking for existing validation comment..."
        
        # Try to find existing comment with our marker
        existing_comment_id=$(gh api \
          "/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments" \
          --jq '.[] | select(.body | contains("<!-- external-pr-validation-comment -->")) | .id' \
          | head -n 1)
        
        if [ -n "$existing_comment_id" ]; then
          echo "Found existing comment (ID: $existing_comment_id), updating..."
          gh api \
            --method PATCH \
            "/repos/${{ github.repository }}/issues/comments/${existing_comment_id}" \
            -f body="$(cat /tmp/validation-comment.md)"
          echo "✅ Updated existing comment"
        else
          echo "No existing comment found, creating new one..."
          gh pr comment "$PR_NUMBER" --repo "${{ github.repository }}" --body-file /tmp/validation-comment.md
          echo "✅ Posted new comment"
        fi
        
        echo "comment-posted=true" >> "$GITHUB_OUTPUT"

